import { requireTenant } from '@/lib/tenant'
import {
  createMaterial, createMaterialCategory, createPurchaseOrderOneLine, createSupplier, createWarehouse,
  postMovement, receivePurchaseLine, saveInventoryPolicy, transferInventory,
} from './actions'
import styles from './inventory.module.css'

const movementLabels:Record<string,string>={receipt:'Entrada',issue:'Salida',return:'Devolución',adjustment_in:'Ajuste +',adjustment_out:'Ajuste -',transfer_in:'Transferencia +',transfer_out:'Transferencia -'}
function money(value:number|null|undefined,currency='PEN'){return value===null||value===undefined?'—':new Intl.NumberFormat('es-PE',{style:'currency',currency}).format(Number(value))}
function date(value:string|null){return value?new Intl.DateTimeFormat('es-PE',{timeZone:'America/Lima',dateStyle:'medium'}).format(new Date(value)):'—'}

export default async function InventoryPage(){
 const {supabase,tenant,role}=await requireTenant();const canManage=['owner','admin','planner','supervisor','warehouse'].includes(role)
 const [{data:units},{data:categories},{data:materials},{data:warehouses},{data:sites},{data:locations},{data:stock},{data:movements},{data:suppliers},{data:poSummary},{data:poLines},{data:purchaseOrders}] = await Promise.all([
  supabase.from('inventory_units').select('id,code,name,symbol').eq('is_active',true).order('name'),
  supabase.from('material_categories').select('id,code,name,parent_id').eq('tenant_id',tenant.id).eq('is_active',true).order('name'),
  supabase.from('materials').select('id,code,name,category_id,unit_id,standard_unit_cost,cost_currency').eq('tenant_id',tenant.id).eq('is_active',true).order('code'),
  supabase.from('warehouses').select('id,code,name,site_id,location_id').eq('tenant_id',tenant.id).eq('is_active',true).order('name'),
  supabase.from('sites').select('id,code,name').eq('tenant_id',tenant.id).order('name'),
  supabase.from('locations').select('id,code,name,site_id,location_type').eq('tenant_id',tenant.id).order('name'),
  supabase.from('inventory_status').select('*').eq('tenant_id',tenant.id).order('warehouse_name').order('material_code'),
  supabase.from('inventory_movements').select('id,code,warehouse_id,material_id,movement_type,quantity_delta,unit_cost,currency,source,reason,occurred_at,work_order_id').eq('tenant_id',tenant.id).order('occurred_at',{ascending:false}).limit(120),
  supabase.from('suppliers').select('id,code,name').eq('tenant_id',tenant.id).eq('is_active',true).order('name'),
  supabase.from('purchase_order_summary').select('*').eq('tenant_id',tenant.id).order('expected_at',{ascending:true}).limit(80),
  supabase.from('purchase_order_lines').select('id,purchase_order_id,material_id,warehouse_id,quantity_ordered,quantity_received,unit_price').eq('tenant_id',tenant.id).order('created_at',{ascending:false}).limit(150),
  supabase.from('purchase_orders').select('id,code,status,currency,supplier_id,expected_at').eq('tenant_id',tenant.id).order('created_at',{ascending:false}).limit(80),
 ])
 const unitRows=units??[],categoryRows=categories??[],materialRows=materials??[],warehouseRows=warehouses??[],siteRows=sites??[],locationRows=locations??[],stockRows=stock??[],movementRows=movements??[],supplierRows=suppliers??[],poRows=poSummary??[],lineRows=poLines??[],orders=purchaseOrders??[]
 const unitMap=new Map(unitRows.map(x=>[x.id,x]));const materialMap=new Map(materialRows.map(x=>[x.id,x]));const warehouseMap=new Map(warehouseRows.map(x=>[x.id,x]));const supplierMap=new Map(supplierRows.map(x=>[x.id,x]));const orderMap=new Map(orders.map(x=>[x.id,x]))
 const below=stockRows.filter(x=>x.stock_status==='below_minimum').length;const reorder=stockRows.filter(x=>x.stock_status==='reorder').length;const reserved=stockRows.reduce((s,x)=>s+Number(x.reserved_quantity??0),0);const pendingPen=poRows.filter(x=>x.currency==='PEN'&&x.status!=='received'&&x.status!=='cancelled').reduce((s,x)=>s+Number(x.pending_amount??0),0)
 return <main className="content stack gap-24">
  <div className="header"><div><span className="badge">Inventario</span><h1>Materiales y almacenes</h1><p className="muted">{tenant.name} · ledger trazable, reservas OT, compras y costos.</p></div><div className={styles.roleChip}>Rol: {role}</div></div>
  <section className={styles.metrics}><div><span>SKU activos</span><strong>{materialRows.length}</strong></div><div><span>Bajo mínimo</span><strong className={below?styles.alert:undefined}>{below}</strong></div><div><span>Reorden</span><strong>{reorder}</strong></div><div><span>Reservado</span><strong>{reserved.toFixed(2)}</strong></div><div><span>Por llegar PEN</span><strong>{money(pendingPen)}</strong></div></section>

  {canManage&&<section className="grid grid-3">
   <form action={createMaterial} className="card stack"><div><strong>Material</strong><p className="muted small">Maestro de repuestos/consumibles.</p></div><div className="form-grid"><input className="input" name="code" placeholder="Código" required/><input className="input" name="name" placeholder="Nombre" required/></div><select className="input" name="unit_id" required defaultValue=""><option value="" disabled>Unidad</option>{unitRows.map(u=><option key={u.id} value={u.id}>{u.symbol} · {u.name}</option>)}</select><select className="input" name="category_id" defaultValue=""><option value="">Sin categoría</option>{categoryRows.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><div className="form-grid"><input className="input" name="standard_unit_cost" type="number" min="0" step="any" placeholder="Costo estándar"/><input className="input" name="cost_currency" defaultValue="PEN" maxLength={3}/></div><input className="input" name="manufacturer" placeholder="Fabricante"/><textarea className="input" name="description" rows={2} placeholder="Descripción"/><button className="button" type="submit">Crear material</button></form>
   <form action={createWarehouse} className="card stack"><div><strong>Almacén</strong><p className="muted small">Ubicación física del stock.</p></div><div className="form-grid"><input className="input" name="code" placeholder="Código" required/><input className="input" name="name" placeholder="Nombre" required/></div><select className="input" name="site_id" defaultValue=""><option value="">Sin fundo específico</option>{siteRows.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select className="input" name="location_id" defaultValue=""><option value="">Sin ubicación específica</option>{locationRows.map(l=><option key={l.id} value={l.id}>{l.code||l.name} · {l.name}</option>)}</select><button className="button" type="submit">Crear almacén</button><div className={styles.miniCatalog}>{warehouseRows.map(w=><span key={w.id}><b>{w.code}</b> {w.name}</span>)}</div></form>
   <form action={saveInventoryPolicy} className="card stack"><div><strong>Política de stock</strong><p className="muted small">Mínimo, máximo y punto de reposición por almacén/material.</p></div><select className="input" name="warehouse_id" required defaultValue=""><option value="" disabled>Almacén</option>{warehouseRows.map(w=><option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select><select className="input" name="material_id" required defaultValue=""><option value="" disabled>Material</option>{materialRows.map(m=><option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select><div className="form-grid"><input className="input" name="minimum_stock" type="number" min="0" step="any" placeholder="Mínimo"/><input className="input" name="maximum_stock" type="number" min="0" step="any" placeholder="Máximo"/></div><div className="form-grid"><input className="input" name="reorder_point" type="number" min="0" step="any" placeholder="Punto reorden"/><input className="input" name="reorder_quantity" type="number" min="0" step="any" placeholder="Cantidad sugerida"/></div><button className="button" type="submit">Guardar política</button></form>
  </section>}

  {canManage&&<section className="grid grid-2">
   <form action={postMovement} className="card stack"><div><strong>Movimiento de stock</strong><p className="muted small">Entrada, devolución o ajuste. El saldo nunca se escribe manualmente.</p></div><div className="form-grid"><select className="input" name="warehouse_id" required defaultValue=""><option value="" disabled>Almacén</option>{warehouseRows.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><select className="input" name="material_id" required defaultValue=""><option value="" disabled>Material</option>{materialRows.map(m=><option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select></div><div className="form-grid"><select className="input" name="movement_type" defaultValue="receipt"><option value="receipt">Entrada</option><option value="return">Devolución</option><option value="adjustment_in">Ajuste +</option><option value="adjustment_out">Ajuste -</option><option value="issue">Salida manual</option></select><input className="input" name="quantity" type="number" min="0.000001" step="any" placeholder="Cantidad" required/></div><div className="form-grid"><input className="input" name="unit_cost" type="number" min="0" step="any" placeholder="Costo unitario opcional"/><input className="input" name="currency" defaultValue="PEN" maxLength={3}/></div><input className="input" name="reason" placeholder="Motivo / documento"/><button className="button" type="submit">Registrar movimiento</button></form>
   <form action={transferInventory} className="card stack"><div><strong>Transferencia</strong><p className="muted small">Genera salida + entrada enlazadas en una sola transacción.</p></div><div className="form-grid"><select className="input" name="from_warehouse_id" required defaultValue=""><option value="" disabled>Origen</option>{warehouseRows.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><select className="input" name="to_warehouse_id" required defaultValue=""><option value="" disabled>Destino</option>{warehouseRows.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></div><select className="input" name="material_id" required defaultValue=""><option value="" disabled>Material</option>{materialRows.map(m=><option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select><input className="input" name="quantity" type="number" min="0.000001" step="any" placeholder="Cantidad" required/><input className="input" name="reason" placeholder="Motivo"/><button className="button" type="submit">Transferir</button></form>
  </section>}

  <section className="card table-card"><div className="section-heading"><div><strong>Stock actual</strong><p className="muted small">Saldo = suma del ledger; disponible = saldo − reservas activas.</p></div></div>{stockRows.length===0?<div className="empty-state"><span className="muted">Registra materiales, almacenes y una entrada inicial.</span></div>:<div className="table-wrap"><table><thead><tr><th>Almacén</th><th>Material</th><th>Stock</th><th>Reservado</th><th>Disponible</th><th>Mínimo</th><th>Estado</th><th>Valor estimado</th></tr></thead><tbody>{stockRows.map((s:any)=><tr key={`${s.warehouse_id}-${s.material_id}`}><td>{s.warehouse_code} · {s.warehouse_name}</td><td><strong>{s.material_code}</strong><div className="muted small">{s.material_name}</div></td><td>{s.quantity_on_hand} {s.unit_symbol}</td><td>{s.reserved_quantity}</td><td><strong>{s.available_quantity}</strong></td><td>{s.minimum_stock}</td><td><span className={`${styles.stockPill} ${s.stock_status==='below_minimum'?styles.danger:s.stock_status==='reorder'?styles.warn:''}`}>{s.stock_status}</span></td><td>{money(s.estimated_stock_value,s.cost_currency)}</td></tr>)}</tbody></table></div>}</section>

  {canManage&&<section className="grid grid-2">
   <form action={createSupplier} className="card stack"><div><strong>Proveedor</strong><p className="muted small">Maestro mínimo para compras.</p></div><div className="form-grid"><input className="input" name="code" placeholder="Código" required/><input className="input" name="name" placeholder="Razón social / nombre" required/></div><div className="form-grid"><input className="input" name="tax_id" placeholder="RUC / ID fiscal"/><input className="input" name="phone" placeholder="Teléfono"/></div><input className="input" name="email" type="email" placeholder="Correo"/><button className="button" type="submit">Crear proveedor</button></form>
   <form action={createPurchaseOrderOneLine} className="card stack"><div><strong>Orden de compra rápida</strong><p className="muted small">La API ya soporta múltiples líneas; esta captura rápida crea una línea.</p></div><div className="form-grid"><select className="input" name="supplier_id" defaultValue=""><option value="">Sin proveedor</option>{supplierRows.map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select><select className="input" name="warehouse_id" defaultValue=""><option value="">Almacén destino</option>{warehouseRows.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></div><select className="input" name="material_id" required defaultValue=""><option value="" disabled>Material</option>{materialRows.map(m=><option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select><div className="form-grid"><input className="input" name="quantity" type="number" min="0.000001" step="any" placeholder="Cantidad" required/><input className="input" name="unit_price" type="number" min="0" step="any" placeholder="Precio unitario" required/></div><div className="form-grid"><input className="input" name="currency" defaultValue="PEN" maxLength={3}/><input className="input" name="expected_at" type="date"/></div><input className="input" name="notes" placeholder="Observación"/><button className="button" type="submit">Crear OC</button></form>
  </section>}

  <section className="card table-card"><div className="section-heading"><div><strong>Compras y por llegar</strong><p className="muted small">Pendiente = ordenado − recibido. La recepción genera stock automáticamente.</p></div></div>{poRows.length===0?<div className="empty-state"><span className="muted">Sin órdenes de compra.</span></div>:<div className="table-wrap"><table><thead><tr><th>OC</th><th>Proveedor</th><th>Estado</th><th>Esperada</th><th>Total</th><th>Recibido</th><th>Por llegar</th><th>Recepción</th></tr></thead><tbody>{poRows.map((po:any)=>{const lines=lineRows.filter(l=>l.purchase_order_id===po.purchase_order_id&&Number(l.quantity_received)<Number(l.quantity_ordered));return <tr key={po.purchase_order_id}><td className="mono">{po.code}</td><td>{supplierMap.get(po.supplier_id)?.name??'—'}</td><td>{po.status}</td><td>{date(po.expected_at)}</td><td>{money(po.order_amount,po.currency)}</td><td>{money(po.received_amount,po.currency)}</td><td><strong>{money(po.pending_amount,po.currency)}</strong></td><td>{canManage&&lines.length? <div className={styles.receiveStack}>{lines.map(line=>{const m=materialMap.get(line.material_id);return <form key={line.id} action={receivePurchaseLine} className="inline-form"><input type="hidden" name="line_id" value={line.id}/><select className="input input-compact" name="warehouse_id" defaultValue={line.warehouse_id??''} required><option value="">Almacén</option>{warehouseRows.map(w=><option key={w.id} value={w.id}>{w.code}</option>)}</select><input className="input input-compact" name="quantity" type="number" min="0.000001" max={Number(line.quantity_ordered)-Number(line.quantity_received)} step="any" placeholder={`${m?.code??''} pend. ${Number(line.quantity_ordered)-Number(line.quantity_received)}`} required/><button className="button button-secondary button-compact" type="submit">Recibir</button></form>})}</div>:<span className="muted">—</span>}</td></tr>})}</tbody></table></div>}</section>

  <section className="card table-card"><div className="section-heading"><div><strong>Ledger de movimientos</strong><p className="muted small">Historial inmutable que explica cada saldo.</p></div></div>{movementRows.length===0?<div className="empty-state"><span className="muted">Sin movimientos.</span></div>:<div className="table-wrap"><table><thead><tr><th>Movimiento</th><th>Fecha</th><th>Almacén</th><th>Material</th><th>Tipo</th><th>Cantidad</th><th>Costo unit.</th><th>Origen</th></tr></thead><tbody>{movementRows.map(m=>{const mat=materialMap.get(m.material_id),wh=warehouseMap.get(m.warehouse_id);return <tr key={m.id}><td className="mono">{m.code}</td><td>{date(m.occurred_at)}</td><td>{wh?.code??'—'}</td><td>{mat?.code??'—'} · {mat?.name??''}</td><td>{movementLabels[m.movement_type]??m.movement_type}</td><td className={Number(m.quantity_delta)<0?styles.negative:styles.positive}>{m.quantity_delta} {mat?unitMap.get(mat.unit_id)?.symbol:''}</td><td>{money(m.unit_cost,m.currency)}</td><td>{m.source}<div className="muted small">{m.reason||''}</div></td></tr>})}</tbody></table></div>}</section>

  {canManage&&categoryRows.length===0&&<form action={createMaterialCategory} className="card inline-form"><input className="input" name="code" defaultValue="REP"/><input className="input" name="name" defaultValue="Repuestos"/><button className="button button-secondary" type="submit">Crear categoría inicial</button></form>}
 </main>
}