import { requireTenant } from '@/lib/tenant'
import { addTeamMember, assignSkill, createSkill, createTeam, createWorker, recordAttendance } from './actions'
import styles from './people.module.css'

export default async function PeoplePage(){
  const {supabase,tenant,role}=await requireTenant()
  const canManage=['owner','admin','planner','supervisor'].includes(role)
  const canAttendance=['owner','admin','supervisor'].includes(role)
  const [{data:workers},{data:statusRows},{data:teams},{data:memberships},{data:skills},{data:workerSkills},{data:attendance},{data:tenantMembers},{data:suppliers}] = await Promise.all([
    supabase.from('workers').select('*').eq('tenant_id',tenant.id).order('employee_code'),
    supabase.from('worker_resource_status').select('*').eq('tenant_id',tenant.id),
    supabase.from('teams').select('*').eq('tenant_id',tenant.id).eq('is_active',true).order('code'),
    supabase.from('team_memberships').select('*').eq('tenant_id',tenant.id).is('valid_to',null),
    supabase.from('skill_catalog').select('*').eq('tenant_id',tenant.id).eq('is_active',true).order('name'),
    supabase.from('worker_skills').select('*').eq('tenant_id',tenant.id),
    supabase.from('worker_attendance').select('*').eq('tenant_id',tenant.id).gte('work_date',new Date(new Date().setDate(new Date().getDate()-31)).toISOString().slice(0,10)).order('work_date',{ascending:false}),
    supabase.from('tenant_members').select('user_id,role,is_active').eq('tenant_id',tenant.id).eq('is_active',true),
    supabase.from('suppliers').select('id,code,name').eq('tenant_id',tenant.id).eq('is_active',true).order('name'),
  ])
  const memberIds=(tenantMembers??[]).map(m=>m.user_id)
  const {data:profiles}=memberIds.length?await supabase.from('profiles').select('id,full_name,email').in('id',memberIds):{data:[]}
  const profileMap=new Map((profiles??[]).map(p=>[p.id,p]))
  const statusMap=new Map((statusRows??[]).map(s=>[s.worker_id,s]))
  const teamMap=new Map((teams??[]).map(t=>[t.id,t]))
  const workerMap=new Map((workers??[]).map(w=>[w.id,w]))
  const skillMap=new Map((skills??[]).map(s=>[s.id,s]))
  const activeWorkers=(workers??[]).filter(w=>w.status==='active')
  const contractors=activeWorkers.filter(w=>w.worker_type==='contractor').length
  const assignedTools=(statusRows??[]).reduce((sum,row)=>sum+Number(row.tools_assigned??0),0)
  const ppeDue=(statusRows??[]).reduce((sum,row)=>sum+Number(row.ppe_due??0),0)
  const certDue=(statusRows??[]).reduce((sum,row)=>sum+Number(row.certifications_expiring_30d??0),0)
  const today=new Date().toISOString().slice(0,10)
  const todayAttendance=(attendance??[]).filter(a=>a.work_date===today)
  const presentToday=todayAttendance.filter(a=>a.status==='present').length

  return <main className="content stack gap-24">
    <div className="header"><div><span className="badge">Personal</span><h1>Técnicos y cuadrillas</h1><p className="muted">{tenant.name} · trabajadores, competencias, recursos y asistencia operativa.</p></div></div>
    <section className={styles.metrics}><div className={styles.metric}><span>Trabajadores activos</span><strong>{activeWorkers.length}</strong></div><div className={styles.metric}><span>Contratistas</span><strong>{contractors}</strong></div><div className={styles.metric}><span>Presentes hoy</span><strong>{presentToday}</strong></div><div className={styles.metric}><span>Herramientas asignadas</span><strong>{assignedTools}</strong></div><div className={styles.metric}><span>EPP / certificados por vencer</span><strong className={(ppeDue+certDue)>0?styles.warn:undefined}>{ppeDue+certDue}</strong></div></section>

    {canManage&&<section className={styles.forms}>
      <form action={createWorker} className="card stack"><div><strong>Nuevo trabajador</strong><p className="muted small">Puede existir sin cuenta de acceso al SaaS.</p></div><div className="form-grid"><input className="input" name="employee_code" placeholder="Código" required/><input className="input" name="full_name" placeholder="Nombre completo" required/></div><div className="form-grid"><select className="input" name="worker_type" defaultValue="employee"><option value="employee">Empleado</option><option value="contractor">Contratista</option></select><input className="input" name="job_title" placeholder="Cargo / función"/></div><select className="input" name="user_id" defaultValue=""><option value="">Sin usuario BRIDATA</option>{(tenantMembers??[]).map(m=>{const p=profileMap.get(m.user_id);return <option key={m.user_id} value={m.user_id}>{p?.full_name||p?.email||m.user_id} · {m.role}</option>})}</select><select className="input" name="supplier_id" defaultValue=""><option value="">Sin empresa contratista</option>{(suppliers??[]).map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select><div className="form-grid"><input className="input" name="email" type="email" placeholder="Correo"/><input className="input" name="phone" placeholder="Teléfono"/></div><div className="form-grid"><input className="input" name="document_id" placeholder="Documento"/><input className="input" name="hire_date" type="date"/></div><button className="button" type="submit">Crear trabajador</button></form>

      <div className="card stack"><form action={createTeam} className={styles.compact}><div><strong>Cuadrilla</strong><p className="muted small">Agrupa personal para asignación operacional.</p></div><div className="form-grid"><input className="input" name="code" placeholder="Código" required/><input className="input" name="name" placeholder="Nombre" required/></div><select className="input" name="supervisor_worker_id" defaultValue=""><option value="">Sin supervisor</option>{activeWorkers.map(w=><option key={w.id} value={w.id}>{w.employee_code} · {w.full_name}</option>)}</select><button className="button button-secondary" type="submit">Crear cuadrilla</button></form>{(teams??[]).length>0&&<form action={addTeamMember} className={styles.compact}><select className="input" name="team_id" required defaultValue=""><option value="" disabled>Cuadrilla</option>{(teams??[]).map(t=><option key={t.id} value={t.id}>{t.code} · {t.name}</option>)}</select><select className="input" name="worker_id" required defaultValue=""><option value="" disabled>Trabajador</option>{activeWorkers.map(w=><option key={w.id} value={w.id}>{w.employee_code} · {w.full_name}</option>)}</select><input className="input" type="date" name="valid_from" defaultValue={today}/><button className="button button-secondary" type="submit">Agregar a cuadrilla</button></form>}</div>

      <div className="card stack"><form action={createSkill} className={styles.compact}><div><strong>Competencias</strong><p className="muted small">Controla capacidades y certificaciones.</p></div><div className="form-grid"><input className="input" name="code" placeholder="Código" required/><input className="input" name="name" placeholder="Competencia" required/></div><input className="input" name="category" placeholder="Categoría"/><button className="button button-secondary" type="submit">Crear competencia</button></form>{(skills??[]).length>0&&<form action={assignSkill} className={styles.compact}><select className="input" name="worker_id" required defaultValue=""><option value="" disabled>Trabajador</option>{activeWorkers.map(w=><option key={w.id} value={w.id}>{w.employee_code} · {w.full_name}</option>)}</select><select className="input" name="skill_id" required defaultValue=""><option value="" disabled>Competencia</option>{(skills??[]).map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select><div className="form-grid"><select className="input" name="level" defaultValue="intermediate"><option value="basic">Básico</option><option value="intermediate">Intermedio</option><option value="advanced">Avanzado</option><option value="expert">Experto</option></select><input className="input" name="certificate_reference" placeholder="Certificado"/></div><div className="form-grid"><input className="input" type="date" name="certified_at"/><input className="input" type="date" name="expires_at"/></div><button className="button button-secondary" type="submit">Asignar competencia</button></form>}</div>

      {canAttendance&&<form action={recordAttendance} className="card stack"><div><strong>Asistencia diaria</strong><p className="muted small">El supervisor registra estado diario; no se pide hora de ingreso/salida.</p></div><select className="input" name="worker_id" required defaultValue=""><option value="" disabled>Trabajador</option>{activeWorkers.map(w=><option key={w.id} value={w.id}>{w.employee_code} · {w.full_name}</option>)}</select><div className="form-grid"><input className="input" name="work_date" type="date" defaultValue={today} required/><select className="input" name="status" defaultValue="present"><option value="present">Presente</option><option value="absent">Ausente</option><option value="leave">Permiso</option><option value="rest">Descanso</option><option value="training">Capacitación</option></select></div><input className="input" name="notes" placeholder="Observación"/><button className="button" type="submit">Registrar asistencia</button></form>}
    </section>}

    <section className="card stack"><div className="section-heading"><div><strong>Personal</strong><p className="muted small">Estado consolidado de recursos y competencias.</p></div></div>{(workers??[]).length===0?<div className="empty-state"><span className="muted">Sin trabajadores.</span></div>:<div className={styles.workerGrid}>{(workers??[]).map(w=>{const s=statusMap.get(w.id);const teamIds=(memberships??[]).filter(m=>m.worker_id===w.id).map(m=>m.team_id);const workerSkillRows=(workerSkills??[]).filter(ws=>ws.worker_id===w.id);return <article className={styles.worker} key={w.id}><div><strong>{w.employee_code} · {w.full_name}</strong><span className={styles.meta}>{w.job_title||'Sin cargo'} · {w.worker_type}{teamIds.length?` · ${teamIds.map(id=>teamMap.get(id)?.code).filter(Boolean).join(', ')}`:''}</span><span className={styles.meta}>{workerSkillRows.map(ws=>skillMap.get(ws.skill_id)?.name).filter(Boolean).join(' · ')||'Sin competencias registradas'}</span></div><div><span className={styles.pill}>{w.status}</span><div className={styles.meta}>{s?.tools_assigned??0} herramientas · {s?.ppe_active??0} EPP</div>{Number(s?.ppe_due??0)+Number(s?.certifications_expiring_30d??0)>0&&<div className={`${styles.meta} ${styles.warn}`}>⚠ {Number(s?.ppe_due??0)+Number(s?.certifications_expiring_30d??0)} vencimientos</div>}</div></article>})}</div>}</section>
  </main>
}