import { requireTenant } from '@/lib/tenant'
import { closePpeIssue, createPpe, createTool, issuePpe, issueTool, returnTool } from './actions'
import styles from './resources.module.css'

function date(value:string|null){return value?new Intl.DateTimeFormat('es-PE',{timeZone:'America/Lima',dateStyle:'medium'}).format(new Date(value)):'—'}

export default async function ResourcesPage(){
  const {supabase,tenant,role}=await requireTenant()
  const canTools=['owner','admin','planner','supervisor','warehouse'].includes(role)
  const canPpe=['owner','admin','supervisor','warehouse'].includes(role)
  const [{data:workers},{data:tools},{data:custody},{data:ppe},{data:issues},{data:warehouses},{data:materials},{data:orders}] = await Promise.all([
    supabase.from('workers').select('id,employee_code,full_name,status').eq('tenant_id',tenant.id).eq('status','active').order('employee_code'),
    supabase.from('tools').select('*').eq('tenant_id',tenant.id).eq('is_active',true).order('code'),
    supabase.from('tool_custody').select('*').eq('tenant_id',tenant.id).order('issued_at',{ascending:false}).limit(120),
    supabase.from('ppe_catalog').select('*').eq('tenant_id',tenant.id).eq('is_active',true).order('code'),
    supabase.from('ppe_issues').select('*').eq('tenant_id',tenant.id).order('issued_at',{ascending:false}).limit(150),
    supabase.from('warehouses').select('id,code,name').eq('tenant_id',tenant.id).eq('is_active',true).order('name'),
    supabase.from('materials').select('id,code,name').eq('tenant_id',tenant.id).eq('is_active',true).order('code'),
    supabase.from('work_orders').select('id,code,title,status').eq('tenant_id',tenant.id).not('status','in','("closed","cancelled")').order('created_at',{ascending:false}).limit(80),
  ])
  const workerMap=new Map((workers??[]).map(w=>[w.id,w]));const toolMap=new Map((tools??[]).map(t=>[t.id,t]));const ppeMap=new Map((ppe??[]).map(p=>[p.id,p]));const warehouseMap=new Map((warehouses??[]).map(w=>[w.id,w]));const materialMap=new Map((materials??[]).map(m=>[m.id,m]));const orderMap=new Map((orders??[]).map(o=>[o.id,o]))
  const available=(tools??[]).filter(t=>t.status==='available').length;const assigned=(tools??[]).filter(t=>t.status==='assigned').length;const toolIssues=(tools??[]).filter(t=>['lost','maintenance'].includes(t.status)).length;const activePpe=(issues??[]).filter(i=>i.status==='active').length;const duePpe=(issues??[]).filter(i=>i.status==='active'&&i.replacement_due&&i.replacement_due<=new Date().toISOString().slice(0,10)).length
  const activeCustody=(custody??[]).filter(c=>c.status==='active')

  return <main className="content stack gap-24">
    <div className="header"><div><span className="badge">Recursos</span><h1>Herramientas y EPP</h1><p className="muted">{tenant.name} · custodia individual, entregas EPP y conexión con inventario.</p></div></div>
    <section className={styles.metrics}><div className={styles.metric}><span>Herramientas disponibles</span><strong className={styles.good}>{available}</strong></div><div className={styles.metric}><span>En custodia</span><strong>{assigned}</strong></div><div className={styles.metric}><span>Mantenimiento / perdidas</span><strong className={toolIssues?styles.bad:undefined}>{toolIssues}</strong></div><div className={styles.metric}><span>EPP activos</span><strong>{activePpe}</strong></div><div className={styles.metric}><span>EPP por reemplazar</span><strong className={duePpe?styles.warn:undefined}>{duePpe}</strong></div></section>

    <section className={styles.forms}>
      {canTools&&<form action={createTool} className="card stack"><div><strong>Nueva herramienta</strong><p className="muted small">Unidad serializada; no se trata como cantidad de inventario.</p></div><div className="form-grid"><input className="input" name="code" placeholder="Código" required/><input className="input" name="name" placeholder="Herramienta" required/></div><div className="form-grid"><input className="input" name="category" placeholder="Categoría"/><input className="input" name="serial_number" placeholder="N° serie"/></div><div className="form-grid"><input className="input" name="manufacturer" placeholder="Fabricante"/><input className="input" name="model" placeholder="Modelo"/></div><select className="input" name="warehouse_id" defaultValue=""><option value="">Sin almacén</option>{(warehouses??[]).map(w=><option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select><div className="form-grid"><select className="input" name="condition" defaultValue="good"><option value="good">Buena</option><option value="fair">Regular</option><option value="poor">Mala</option><option value="damaged">Dañada</option></select><input className="input" name="acquired_at" type="date"/></div><button className="button" type="submit">Crear herramienta</button></form>}
      {canTools&&<form action={issueTool} className="card stack"><div><strong>Entregar herramienta</strong><p className="muted small">Una herramienta solo puede tener una custodia activa.</p></div><select className="input" name="tool_id" required defaultValue=""><option value="" disabled>Herramienta disponible</option>{(tools??[]).filter(t=>t.status==='available').map(t=><option key={t.id} value={t.id}>{t.code} · {t.name}</option>)}</select><select className="input" name="worker_id" required defaultValue=""><option value="" disabled>Trabajador</option>{(workers??[]).map(w=><option key={w.id} value={w.id}>{w.employee_code} · {w.full_name}</option>)}</select><select className="input" name="work_order_id" defaultValue=""><option value="">Sin OT específica</option>{(orders??[]).map(o=><option key={o.id} value={o.id}>{o.code} · {o.title}</option>)}</select><input className="input" name="notes" placeholder="Observación"/><button className="button" type="submit">Entregar</button></form>}
      {canPpe&&<form action={createPpe} className="card stack"><div><strong>Catálogo EPP</strong><p className="muted small">Puede vincularse a un material para descontar stock al entregar.</p></div><div className="form-grid"><input className="input" name="code" placeholder="Código" required/><input className="input" name="name" placeholder="EPP" required/></div><select className="input" name="material_id" defaultValue=""><option value="">Sin material de inventario</option>{(materials??[]).map(m=><option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select><div className="form-grid"><input className="input" name="replacement_days" type="number" min="1" placeholder="Reemplazo cada días"/><input className="input" name="certification_standard" placeholder="Norma/certificación"/></div><label className="muted small"><input type="checkbox" name="requires_size"/> Requiere talla</label><button className="button" type="submit">Crear EPP</button></form>}
      {canPpe&&<form action={issuePpe} className="card stack"><div><strong>Entregar EPP</strong><p className="muted small">Si está ligado a inventario, la entrega genera una salida de stock.</p></div><select className="input" name="ppe_id" required defaultValue=""><option value="" disabled>EPP</option>{(ppe??[]).map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select><select className="input" name="worker_id" required defaultValue=""><option value="" disabled>Trabajador</option>{(workers??[]).map(w=><option key={w.id} value={w.id}>{w.employee_code} · {w.full_name}</option>)}</select><select className="input" name="warehouse_id" defaultValue=""><option value="">Almacén si usa stock</option>{(warehouses??[]).map(w=><option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select><div className="form-grid"><input className="input" name="quantity" type="number" min="0.000001" step="any" defaultValue="1" required/><input className="input" name="size" placeholder="Talla"/></div><input className="input" name="notes" placeholder="Observación"/><button className="button" type="submit">Entregar EPP</button></form>}
    </section>

    <section className="card stack"><div className="section-heading"><div><strong>Herramientas</strong><p className="muted small">Estado y custodia actual.</p></div></div>{(tools??[]).length===0?<div className="empty-state"><span className="muted">Sin herramientas.</span></div>:<div className={styles.resourceGrid}>{(tools??[]).map(t=>{const c=activeCustody.find(row=>row.tool_id===t.id),w=c?workerMap.get(c.worker_id):null;return <article className={styles.resource} key={t.id}><div><strong>{t.code} · {t.name}</strong><span className={styles.meta}>{t.category||'Sin categoría'} · {t.serial_number||'sin serie'} · {warehouseMap.get(t.current_warehouse_id)?.code||''}</span>{w&&<span className={styles.meta}>Custodia: {w.employee_code} · {w.full_name}{c?.work_order_id?` · ${orderMap.get(c.work_order_id)?.code||'OT'}`:''}</span>}</div><div><span className={styles.status}>{t.status}</span><div className={styles.meta}>{t.condition}</div></div></article>})}</div>}</section>

    {canTools&&activeCustody.length>0&&<section className="card stack"><div><strong>Retornos pendientes</strong></div>{activeCustody.map(c=>{const t=toolMap.get(c.tool_id),w=workerMap.get(c.worker_id);return <form action={returnTool} className={styles.returnForm} key={c.id}><input type="hidden" name="custody_id" value={c.id}/><div><strong>{t?.code} · {t?.name}</strong><div className={styles.meta}>{w?.full_name} · desde {date(c.issued_at)}</div></div><select className="input" name="condition" defaultValue="good"><option value="good">Buena</option><option value="fair">Regular</option><option value="poor">Mala</option><option value="damaged">Dañada</option></select><select className="input" name="outcome" defaultValue="returned"><option value="returned">Devuelta</option><option value="damaged">A mantenimiento</option><option value="lost">Perdida</option></select><button className="button button-secondary" type="submit">Cerrar custodia</button></form>})}</section>}

    <section className="card stack"><div className="section-heading"><div><strong>Entregas EPP</strong><p className="muted small">Histórico por trabajador y próxima reposición.</p></div></div>{(issues??[]).length===0?<div className="empty-state"><span className="muted">Sin entregas EPP.</span></div>:<div className={styles.issueList}>{(issues??[]).map(i=>{const p=ppeMap.get(i.ppe_id),w=workerMap.get(i.worker_id),mat=p?.material_id?materialMap.get(p.material_id):null;return <article className={styles.issue} key={i.id}><div><strong>{p?.code} · {p?.name}</strong><span className={styles.meta}>{w?.employee_code} · {w?.full_name} · {i.quantity}{i.size?` · talla ${i.size}`:''}{mat?` · stock ${mat.code}`:''}</span><span className={styles.meta}>Entregado {date(i.issued_at)} · reposición {i.replacement_due||'sin fecha'}</span></div><div><span className={`${styles.status} ${i.status==='active'&&i.replacement_due&&i.replacement_due<=new Date().toISOString().slice(0,10)?styles.warn:''}`}>{i.status}</span>{canPpe&&i.status==='active'&&<form action={closePpeIssue} className="stack"><input type="hidden" name="issue_id" value={i.id}/><select className="input input-compact" name="status" defaultValue="replaced"><option value="replaced">Reemplazado</option><option value="returned">Devuelto</option><option value="lost">Perdido</option><option value="disposed">Desechado</option></select><button className="button button-secondary button-compact" type="submit">Cerrar</button></form>}</div></article>})}</div>}</section>
  </main>
}